### ISSUE TITLE
test_get_stats fails on hasoffers live

### ISSUE THREAD

**Issue by parasquid** [sportngin/hasoffers#1]
Instead of arrays, HasOffers prefers something like this:

response = HasOffers::Report.get_stats('fields' =>  ['Stat.clicks', 'Stat.payout'], 'filters' => {'Stat.affiliate_id' => {'conditional' => 'EQUAL_TO', 'values' => 1119}});nil

Also, as tested on Rails 3.1, the method 'to_params' is replaced by 'to_param' and the call to query_string will fail if this isn't monkey-patched.

I'll send a pull-request in a few days.

**Comment by kjbkjb** [comment]
Sport Ngin has discontinued support for this gem. We regret any inconvenience.
