### ISSUE TITLE
Fetching Category

### ISSUE THREAD

**Issue by technotip** [sportngin/hasoffers#16]
We can get all the category name and category ids from 'Affiliate_Application :: findAllOfferCategories'
But there doesn't seem to be a way we can pass-in this category_id and fetch all the corresponding offers :-(

Please enlighten me on this!

**Comment by jphenow** [comment]
That may be a limitation of the API... I took a quick glance at [their API docs](http://developers.hasoffers.com/#/brand) and didn't see anything but its possible I was misunderstanding you or reading too quickly. If you'd like to take a look and suggest a change (or submit a PR), you're more than welcome to do so!

**Comment by technotip** [comment]
Ya there is no way to fetch offers based on category id.

How can I submit request for this feature?
Am not so familiar with github yet. Can someone help.

Thanks ..

**Comment by technotip** [comment]
I want to have API to fetch offer id's based on Category_id.
i.e., we need to be able to fetch offers of particular category, by passing category_id

Please help with this as soon as possible ..thanks

**Comment by ChrisArcand** [comment]
As @jphenow already mentioned, you should confirm that the hasoffers API actually supports this behavior. You can do that by looking through their API docs or asking them directly. 

If they do, you could then point that out here and even suggest a change in behavior.

If you need it very urgently, you are welcome to implement this feature yourself and open a pull request.

**Comment by kjbkjb** [comment]
Sport Ngin has discontinued support for this gem. We regret any inconvenience.
