### ISSUE TITLE
Excessive validations for Affiliate

### ISSUE THREAD

**Issue by troessner** [sportngin/hasoffers#6]
According to http://www.hasoffers.com/wiki/Api_Model:Affiliate only `company` and `id` is required (no idea why the hell `id` is there, but let's just ignore that for now).
However, the gem validates for a lot of the optional parameters as well:

https://github.com/sportngin/hasoffers/blob/master/lib/hasoffers/affiliate.rb#L10

As you can see it also validates:

>> requires!(data, %w[company address1 city country zipcode phone])

Is this indeed a bug or am I missing something here?

**Comment by kjbkjb** [comment]
Sport Ngin has discontinued support for this gem. We regret any inconvenience.
